### ISSUE TITLE
Firefox omnibox bar remains focused upon pressing Enter

### ISSUE THREAD

**Issue by brainplot** [huhu/rust-search-extension#102]
Hi there! I really love this extension but there's one little thing that's slightly inconvenient to deal with, at least in my opinion.

Whenever you hit Enter to perform a search, Firefox's omnibox bar remains focused as if I had just clicked on it in order to input some text. I have to click on the actual page to give it focus. Luckily I can still scroll even though the omnibox is focused but the keyboard shortcuts defined by the page wouldn't of course work.

I'm attaching a screen recording to better show what I mean. Is this intended behavior?

https://user-images.githubusercontent.com/28014843/107144270-6517a480-693a-11eb-89ae-bfcf7f039594.mov

**Comment by Folyd** [comment]
Hi @brainplot. Thanks for reporting. This is the default behavior for the browser plugin. AFAIK, we have no API to change this. However, you can combine `Alt` or `Cmd` (if you are a Mac user) with `Enter` to open the search result in the new tab.

**Comment by brainplot** [comment]
Hi @Folyd and thanks for the quick response!

That's bummer. I'll take your suggestion, even though I wish I didn't have to do that. I already open too many browser tabs as it is! 🙂

It would be great to modify this behavior if an API for it ever comes out. I guess we'll have to close this for now though!

**Comment by Folyd** [comment]
Ok.  Feel free to file another issue if you have any further questions. :)
