### ISSUE TITLE
How to set offline path to 'localhost/rust/'?

### ISSUE THREAD

**Issue by XyLyXyRR** [huhu/rust-search-extension#105]
Hi, there. I just known this project. It's so awesome.

I saw offline mode, and I want set it to offline mode. I had configured nginx, route `localhost/rust/` to doc path. But I can't use this path in this extension. Could you change path match Regex to `(^https?://)?.*(:\d{2,6})?.*`? This one should works better.

**Comment by Folyd** [comment]
Hi @XyLyXyRR. Thanks for your suggestion. Sounds good. I never aware people would configure an Nginx for the local docs path. The next version that release soon will fix this. 🍺
