### ISSUE TITLE
https://rust.extension.sh has an incorrect # link: #add-crate-to-extension

### ISSUE THREAD

**Issue by peter-kehl** [huhu/rust-search-extension#111]
Hi.
"After you add the crate to extension" links to #add-crate-to-extension, which is incorrect. The correct link should be to #add-your-favorite-crate-to-extension. (To check, see https://rust.extension.sh/#add-crate-to-extension versus https://rust.extension.sh/#add-your-favorite-crate-to-extension).

**Comment by Folyd** [comment]
Good catch! Thanks a lot.
