### ISSUE TITLE
I have no idea how to use this on firefox

### ISSUE THREAD

**Issue by iMplode-nZ** [huhu/rust-search-extension#117]
I'd appreciate if the documentation actually said how to use it.

**Comment by Folyd** [comment]
> I'd appreciate if the documentation actually said how to use it.

Hi @iMplode-nZ. Thanks for the feedback. Did you check the [https://rust.extension.sh/](https://rust.extension.sh/)? 

You should input the keyword **rs** then press **Space** in the address bar to get started. Just that easy!

**Comment by iMplode-nZ** [comment]
I did check it out, but for some reason `rs ` didn't work.

**Comment by Folyd** [comment]
> I did check it out, but for some reason `rs ` didn't work.

That's weird. Can you give some screenshots to help with the diagnostics?

**Comment by iMplode-nZ** [comment]
Huh, now it works.
