### ISSUE TITLE
Inconsistent toolbar button description

### ISSUE THREAD

**Issue by peter-kehl** [huhu/rust-search-extension#118]
**Summary**
Please change the description "The ultimate search extension for Rust" to "Rust Search Extension", to be consistent.

**Explanation**
The Firefox extension (and maybe other ones, too) has a toolbar button/icon with a description "The ultimate search extension for Rust". People with many extensions (I have 80+) can't have all the extension buttons on the browser toolbar. In Firefox we can move selected extension buttons to the the "Overflow Menu" (which looks like >> and it opens a dropdown).

The Overflow Menu lists the buttons and their descriptions. Since buttons are often small for people to recognize, it can be easier to find the relevant button by description.

The list of installed extensions (Firefox special url about:addons) and https://rust.extension.sh/update call this extension "Rust Search Extension". However, that is different from description "The ultimate search extension for Rust". That difference makes it difficult to locate the icon in the "Overflow Menu".

**Comment by Folyd** [comment]
Makes sense. I changed the description to `Rust Search Extension - the ultimate search extension for Rust`. I think this fits your need. Thanks for the feedback.
