### ISSUE TITLE
Sometimes can't update crate version

### ISSUE THREAD

**Issue by XyLyXyRR** [huhu/rust-search-extension#119]
Hi, there.

Sometimes I can't update crate version. [teloxide](https://docs.rs/teloxide) just release `0.4.0` two days age. But I can't add this version to this extension, but old version like `0.3.4` is fine. 

In addition, could you add a export feature? If I reinstall this extension, crate list will be empty.

**Comment by Folyd** [comment]
Thanks for the feedback. 

> Sometimes I can't update crate version. teloxide just release 0.4.0 two days age. But I can't add this version to this extension, but old version like 0.3.4 is fine.

Seems like this is a `librustdoc` incompatibility bug. Currently, a possible workaround:
- Click the docs.rs's search box (in **teloxide** page) in advance  (this will trigger the search-index load)
- Click `+ to Rust Search Extension` button

> In addition, could you add a export feature? If I reinstall this extension, crate list will be empty.

Good idea. I'll add it ASAP. Stay tuned!

**Comment by Folyd** [comment]
This has been fixed in **v1.3.1**.
