### ISSUE TITLE
search clippy lints

### ISSUE THREAD

**Issue by songzhi** [huhu/rust-search-extension#12]
[clippy lints](https://rust-lang.github.io/rust-clippy/master/index.html) 
This site has anchors,so searching would work.

**Comment by Folyd** [comment]
Thanks for the suggestion. I don't know in what case do people need search clippy hints? Could you please give an example?

**Comment by songzhi** [comment]
When using intellij-rust and Clippy as linter,the intellij-rust will show clippy lints for non-perfect code.People can use rust-search-extension search the detailed infomation about it.

**Comment by Folyd** [comment]
Sounds good. It could be in the next development plan.

**Comment by Folyd** [comment]
Hey @songzhi. Version 0.9.0 with Clippy lint searching is released!  😄
