### ISSUE TITLE
add crate report Uncaught TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by Sherlock-Holo** [huhu/rust-search-extension#120]
I try to add `io-uring` crate but extension report
> Uncaught TypeError: Cannot read property 'value' of undefined

![image](https://user-images.githubusercontent.com/10096425/122861269-beb0c680-d351-11eb-8ad3-a77425288220.png)

the extension version is 1.2.1

**Comment by Folyd** [comment]
Thanks for reporting. This is a known issue. A possible workaround: https://github.com/huhu/rust-search-extension/issues/119#issuecomment-861173120

**Comment by Folyd** [comment]
This has been fixed in **v1.3.1**.
