### ISSUE TITLE
can't add 'gtk4'

### ISSUE THREAD

**Issue by XyLyXyRR** [huhu/rust-search-extension#121]
![image](https://user-images.githubusercontent.com/39663597/125228917-401fc700-e308-11eb-9082-b7b8beb17c0a.png)

**Comment by Folyd** [comment]
Thanks for the feedback! The error: `The message port closed before a response was received` is an internal error raised from Chrome itself. Restart or upgrade the Chrome browser may fix this.

**Comment by XyLyXyRR** [comment]
Maybe my ssd is unhappy, I reinstalled this, it works fine.
