### ISSUE TITLE
Scrolling on crate's docs.rs index doc page is broken

### ISSUE THREAD

**Issue by cdmistman** [huhu/rust-search-extension#122]
Browser: chrome 92.0.4515.131 (Official Build) (64-bit) (cohort: 92_win_131)
Extension version: 1.3.0

Description: When trying to view the index page for a crate's documentation, 2 unexpected behaviors occur. When the page is first loaded, scrolling starts at the bottom of the page. The second unexpected behavior is when attempting to scroll up using the mouse wheel - after a certain (small) amount of travel, the scroll goes back to the bottom of the page.

Steps to reproduce:
1. Ensure the extension is enabled
2. go to <https://docs.rs/tokio/1.9.0/tokio>
3. Attempt to scroll up via mouse wheel

Image: 
![image](https://user-images.githubusercontent.com/23486351/128215988-fdc65cbd-f4c8-42c7-be74-ac0c06639432.png)

Note that this occurs regardless of window orientation (I first noticed on my vertical monitor, but confirmed on my horizontal monitor), and persists after both revoking <https://docs.rs> cache and cookies, as well as rebooting. The behavior is as expected when the extension is disabled.

**Comment by Folyd** [comment]
Hugely thanks for the report! I'll try to reproduce this and fix it ASAP.
