### ISSUE TITLE
docs.rs sometimes don't allow you to go to the top of the page

### ISSUE THREAD

**Issue by ZetaNumbers** [huhu/rust-search-extension#123]
I am using Firefox 90.0.2 64bit on win10. I was on https://docs.rs/object/0.26.0/object/ and couldn't go to the top of the page, it just scrolls down again. After uninstalling the extension (or going private mode) it fixes itself.

**Comment by brainplot** [comment]
I just ran into the same thing on https://docs.rs/hyper/0.14.11/hyper/struct.Uri.html. Can you test this page as well just to confirm we're talking about the same issue?

**Comment by ZetaNumbers** [comment]
> I just ran into the same thing on https://docs.rs/hyper/0.14.11/hyper/struct.Uri.html. Can you test this page as well just to confirm we're talking about the same issue?

No, i can't. Sorry. I am unable to reproduce mine too.

**Comment by Folyd** [comment]
Thanks for the feedback. I uploaded a **v1.3.1** here. Would you mind giving it a try? This bug should be fixed I think. If not, please let me know. @ZetaNumbers @brainplot @cdmistman 
[firefox-rust-search-extension-1.3.1.zip](https://github.com/huhu/rust-search-extension/files/6942721/firefox-rust-search-extension-1.3.1.zip)
[chrome-rust-search-extension-1.3.1.zip](https://github.com/huhu/rust-search-extension/files/6942722/chrome-rust-search-extension-1.3.1.zip)

**Comment by cdmistman** [comment]
> [chrome-rust-search-extension-1.3.1.zip](https://github.com/huhu/rust-search-extension/files/6942722/chrome-rust-search-extension-1.3.1.zip)

This works as expected using the link that was broken in my issue as well as the links listed in this issue. thank you so much!

**Comment by brainplot** [comment]
I'm unable to try that new version. I'm not familiar with how browser extensions work but I tried to import the Firefox zip into my Firefox installation in `about:addons > Install Add-on from File...` and I got a message saying "This add-on could not be installed because it appears to be corrupt".

**Comment by Folyd** [comment]
@brainplot Try `about:addons > Debug Add-ons`. 😄

**Comment by brainplot** [comment]
Yep, I can confirm it's fixed for Firefox too. Thank you @Folyd!

Also appreciated the instructions 😄

**Comment by ZetaNumbers** [comment]
I think i found the reason. I use 5:4 display. When there's no space for a side table of contents, it drops down below the main content. 
![изображение](https://user-images.githubusercontent.com/53300196/128481429-81df6a7e-02f1-45ca-924f-8c32d747db69.png)

> [firefox-rust-search-extension-1.3.1.zip](https://github.com/huhu/rust-search-extension/files/6942721/firefox-rust-search-extension-1.3.1.zip)
Sorry, firefox says it is corrupted.

**Comment by ZetaNumbers** [comment]
I followed instructions above about debug extension. It's fixes it only if you don't resize your window after a reload. So i guess that's not ideal but enough for me.

**Comment by brainplot** [comment]
>  I use 5:4 display

For reference, I'm using a 13" MacBook Pro, which has a 16:10 screen.

**Comment by cdmistman** [comment]
> It's fixes it only if you don't resize your window after a reload. So i guess that's not ideal but enough for me.

This case isn't broken for me. 16:9 screen turned vertical

**Comment by Folyd** [comment]
So I guess we have no problem remain, right? I'll upload the **v1.3.1** to the Webstore and AMO.

**Comment by ZetaNumbers** [comment]
> It's fixes it only if you don't resize your window after a reload.

Someone will open another issue if it would be a problem to them.
