### ISSUE TITLE
"File not found" when clicking the extension icon

### ISSUE THREAD

**Issue by brainplot** [huhu/rust-search-extension#124]
Hi there, I just installed v1.3.1 from the Firefox extension store after following #123. I can confirm from the `about:addons` page that `v1.3.1` is the one that's installed.

However, clicking on the extension in the browser toolbar gives me a "File not found" page with this address: `moz-extension://fa9cb326-ee80-ab42-926a-3e6db96d1979/manage/index.html`.

I'm attaching a screenshot below:

![Screen Shot 2021-08-07 at 1 13 49 AM](https://user-images.githubusercontent.com/28014843/128579444-86fd0052-9187-473d-b6f3-f6cf7f5c528a.png)

**Edit**: I also tried restarting the browser but the problem persisted.

**Comment by Folyd** [comment]
Holy shit! This is a stupid bug. I added [some assertions](https://github.com/huhu/rust-search-extension/commit/fdfc109ae495ca1e01500a72eabf6589dc3f8065) to prevent such bugs again! Thanks for the feedback. 👍
