### ISSUE TITLE
Error when adding nalgebra to indexed crates

### ISSUE THREAD

**Issue by samoylovfp** [huhu/rust-search-extension#126]
Extension Version 1.3.2

Firefox 91.0.2 (64-bit)
Ubuntu 20.04.3 LTS \n \l
On https://docs.rs/nalgebra/0.29.0/nalgebra/ clicking on "to Rust Search Extension" button shows red cross on the button and this traceback in the console:
```
Oops! We have failed to install this crate! 
Object { pathname: "/nalgebra/0.29.0/nalgebra/", crateVersion: "0.29.0", installedVersion: undefined, data: {…} }
docs-rs.js:218:29
    <anonymous> moz-extension://8af25eb8-3c64-4528-9928-f01dac9095ba/script/docs-rs.js:218
```

P.S. Thanks for maintaining this awesome extension!

**Comment by Folyd** [comment]
Hi @samoylovfp. Thanks for reporting. That's weird. Did you tried to restart Firefox and reinstall it again? 🤔

**Comment by samoylovfp** [comment]
Restarting didn't help, but reinstalling the extension did! Weird glitch though. Didn't happen with other crates, tried with macroquad and ndarray.
Thanks again!
