### ISSUE TITLE
[Req] lib.rs support

### ISSUE THREAD

**Issue by Geobert** [huhu/rust-search-extension#13]
Hi, thank you for this handy addon!

Are there any plans to have the choice to use lib.rs instead of crates.io?

Regards

**Comment by Folyd** [comment]
Let me give my understanding, what you mean is when you select a crate search result in the address bar, jump to lib.rs's link instead of creates.io's link?

**Comment by Geobert** [comment]
yes :)

**Comment by Folyd** [comment]
Ok, I see. Anyway, please forgive me ask why you prefer lib.rs than crates.io. In personally, I don't think lib.rs any better than crates.io. Could you please tell something? Thanks.

**Comment by Geobert** [comment]
Mostly for the dark theme ^^' And the layout feels more modern as well. It's a matter of personal taste so it might not worth the effort, which I would totally understand :)

**Comment by Folyd** [comment]
Hi @Geobert. We just released **v0.10.0** today. You can customize your crate search platform (crates.io or lib.rs) on the popup page. 🎉🎉 See the [changelog](https://rust-search-extension.now.sh/changelog/).
