### ISSUE TITLE
Stopped working in Firefox Nightly

### ISSUE THREAD

**Issue by heftig** [huhu/rust-search-extension#132]
The extension recently stopped working in my Firefox Nightly. I don't know whether it was a browser update or an extension update.

Entering `rs path` in the address bar only shows a single extension entry "Rust Search Extension — rs path", pressing Enter just clears the address bar.

The extension's console contains an error:

```
[4238.375] [WS-2]: handleError 
Event { isTrusted: true, type: "error", target: WebSocket, srcElement: WebSocket, currentTarget: null, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, … }
logger.ts:44:44
    error logger.ts:44
    handleError websocket.ts:77
```

**Comment by Folyd** [comment]
Hi @heftig. Thanks for the feedback. I can't reproduce it on my machine. 
```
[4238.375] [WS-2]: handleError 
Event { isTrusted: true, type: "error", target: WebSocket, srcElement: WebSocket, currentTarget: null, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, … }
logger.ts:44:44
    error logger.ts:44
    handleError websocket.ts:77
```
Seems this error is irrelative to the extension. Did you try to restart Firefox or reinstall the extension? Also see #130.

**Comment by heftig** [comment]
Well, I had already tried both multiple times.

Today, the extension was suddenly missing. Upon reinstall, all its settings got reset and the extension is working again. Bizarre.

Sorry for the noise.
