### ISSUE TITLE
No search index found, start loading...

### ISSUE THREAD

**Issue by char-name** [huhu/rust-search-extension#134]
'Add to Rust Search Extension' button is not working

![image](https://user-images.githubusercontent.com/45714963/144872570-5d0a848d-0095-457f-89ed-c52f9e2110f5.png)
![image](https://user-images.githubusercontent.com/45714963/144872644-83ad5c27-105e-42a2-8c23-c9550b4d9f5e.png)

MS Edge 96.0.1054.43
Extension version: 1.4.0

**Comment by Folyd** [comment]
Hi @char-name. Which crates?

**Comment by char-name** [comment]
Both `rand` and `axum` are in the same situation

**Comment by Folyd** [comment]
> Both `rand` and `axum` are in the same situation

Thanks. This has been fixed. I'll release a new version today.
