### ISSUE TITLE
Wrong crate is selected when searching

### ISSUE THREAD

**Issue by surban** [huhu/rust-search-extension#136]
Hi, 

I am the author of two crates called `bluer` and `remoc`. Both are listed on crates.io and have documentation on docs.rs.

However, when typing `rs bluer` I am always redirected to the docs page of `bluez`. And when typing `rs remoc` I always get redirected to `wiremock`. 

Is there something I have to do to get the crates included in Rust search extension?
I like the extension very much, but it's a bit cumbersome if I cannot use it to open the docs of my own crates.

**Comment by Folyd** [comment]
Hi, @surban.  Glad you like my rust extension. :)

> Is there something I have to do to get the crates included in Rust search extension?

Currently, we only index the [top 20K crates](https://rust.extension.sh/#search-top-20k-crates) (ranked by the download times). I'm sorry that `bluer` and `remoc` are not included right now. I'm considering expanding the number to the top 30K though.
