### ISSUE TITLE
Not work on chrome96!

### ISSUE THREAD

**Issue by gb880327** [huhu/rust-search-extension#137]
![2021-12-16 at 9 06 AM](https://user-images.githubusercontent.com/4083087/146289126-22402e29-ce43-4956-8f4d-905e971fe0c2.png)

**Comment by Folyd** [comment]
Thanks for the feedback. This has been fixed. I'll release a new version ASAP.
The quick workaround is to replace the URL path of docs.rs from `/[crate]/latest` to `/[crate]/[version]`.
See https://github.com/huhu/rust-search-extension/issues/135.
