### ISSUE TITLE
rust docs enhancement

### ISSUE THREAD

**Issue by NaturelLee** [huhu/rust-search-extension#139]
rust docs enhancement

1. https://doc.rust-lang.org/*
2. https://docs.rs/*

![image](https://user-images.githubusercontent.com/12494855/149136966-3534dbd6-6d61-4b22-a033-5d772fc1a123.png)

**Comment by Folyd** [comment]
Close via #140

**Comment by xnuk** [comment]
Thanks for your work, but I personally don't like this (so I disabled the extension temporarily). I don't think that tweaking CSS for rustdoc should not be in the scope of "search extension"; I think [docs.rs repository] is a good place to talk similar topics like this.

[docs.rs repository]: https://github.com/rust-lang/docs.rs/

**Comment by Folyd** [comment]
> Thanks for your work, but I personally don't like this (so I disabled the extension temporarily). I don't think that tweaking CSS for rustdoc should not be in the scope of "search extension"; I think [docs.rs repository](https://github.com/rust-lang/docs.rs/) is a good place to talk similar topics like this.

Personally, I prefer to keep it under a setting item, and the user needs to turn it on (disabled by default), but that adds complexity to this extension.

**Comment by NaturelLee** [comment]
It's better to provide options to disable the layout highlight.   
Honestly speaking, it's a little ugly with white lines. Green or other theme related color can be better.

**Comment by Folyd** [comment]
Actually, it's only white (`#ddd`) for old rust docs. The new version of rust docs which with the `html[data-theme]` attribute would have an adaptive color.

https://github.com/huhu/rust-search-extension/blob/2879e9a460a269dd13f4f27441b348a70d40ef30/extension/script/details-toggle.css

**Comment by NaturelLee** [comment]
![image](https://user-images.githubusercontent.com/12494855/151307974-4db54423-ff23-4d7b-ba5f-6bf24d101f23.png)

这三种颜色看起来差不多。并且颜色有点儿亮，相比于内容区域太突出了。
![image](https://user-images.githubusercontent.com/12494855/151308658-08abb1ba-f4e8-4f52-9389-05b680564470.png)

这样看就有点儿费眼了
