### ISSUE TITLE
[feature request] search all docs both in std or external crates by default

### ISSUE THREAD

**Issue by jiacai2050** [huhu/rust-search-extension#141]
Currently, we have to use special  prefix(`~`) to search external crates, it would be great if this extension would search both std docs and external crates by default (or at least provide a setting).

**Comment by jiacai2050** [comment]
![image](https://user-images.githubusercontent.com/3848910/149658795-98e6b685-b627-4149-97c6-280dbb29e9c4.png)
This is what is look like in [dash](https://kapeli.com/dash), it will search all docsets by default.

**Comment by Folyd** [comment]
Thanks, @jiacai2050. Sounds like a good idea. Actually, it is pretty easy to support this. Just two lines change required. 😄 However, we need a setting to turn it on. (Yes, disabled by default). What do you think?

```diff
// main.js
omnibox.addPrefixQueryEvent("~", {
+       defaultSearch: true,
+       searchPriority: 3,
        onSearch: (query) => {
            return crateDocSearcher.searchAll(query);
        },
}

```

![image](https://user-images.githubusercontent.com/3369694/149666748-bcafebcf-e5cd-4b02-b822-2ce168d31654.png)

**Comment by jiacai2050** [comment]
Add another settings(disabled by default) seems fine to me as it keeps backward compatibility. 

We can change this behavior later when we have more confidence.

**Comment by Folyd** [comment]
![image](https://user-images.githubusercontent.com/3369694/150687379-dbc399a4-d6ca-479d-be04-d64f192ebd66.png)

This feature is supported in the next version. Stay tuned.
