### ISSUE TITLE
Can no longer search std docs

### ISSUE THREAD

**Issue by tuxmark5** [huhu/rust-search-extension#143]
I'm using Chrome 97.0.4692.71 with Rust Search Extension 1.5.0 and can no longer find anything in `std`. Searching external crates works fine. For example entering `rs thread` shows a list of crates instead of searching through std. Disabling "docs.rs" search in settings and then searching `rs thread` yields an empty result list.

**Comment by Folyd** [comment]
That's weird. Could you please provide some error logs to help diagnose?
> Open `chrome://extensions/` page, and enable developer mode, then you should see a `background` link in the `Rust Search Extension` card. Click the `background` link to open the inspect console. I hope you can find the error log on the console tab.
![image](https://user-images.githubusercontent.com/3369694/151472374-e7cdd59c-dd0d-48ff-a158-d09075b52946.png)

**Comment by tuxmark5** [comment]
I just fired up chrome to try to reproduce the issue, but it seems to work fine now. If the issue pops up again, I'll try to get the error log from the background page.

**Comment by Folyd** [comment]
I'll close it now, feel free to reopen the issue if you get the problem again. :)
