### ISSUE TITLE
Revert border on `impl` blocks

### ISSUE THREAD

**Issue by Rapptz** [huhu/rust-search-extension#144]
There was a recent change that added borders to `impl` blocks:

![image](https://user-images.githubusercontent.com/1695103/151646831-35c608ab-c362-45b5-abf7-b1fbad0a6c29.png)

Would it be possible to revert this? Personally it's very distracting and has too much visual clutter.

**Comment by Folyd** [comment]
Hi @Rapptz. We had some discussion in #139 before. After my experiments, I found a good alternative is hovering to show the left border. I believe this brings no distraction while still showing highlight effects. Also, it doesn't add complexity to the extension.

```diff
-details.rustdoc-toggle:not(.top-doc) {
-    border: 1px solid #ddd;
-    margin-top: 5px;
-    padding: 5px;
+.impl-items>details.rustdoc-toggle {
+    border: 2px solid transparent;
+    padding-left: 5px;
 }
 
-html[data-theme="ayu"] details.rustdoc-toggle:not(.top-doc) {
-    border-color: #5c6773;
-}
-
-html[data-theme="dark"] details.rustdoc-toggle:not(.top-doc) {
-    border-color: #d2d2d2;
-}
-
-html[data-theme="light"] details.rustdoc-toggle:not(.top-doc) {
-    border-color: #ddd;
+.impl-items>details.rustdoc-toggle:hover {
+    border-left: 2px solid #F9BB2DAA;
+    padding-left: 5px;
 }
```

The border-left color `#F9BB2DAA` is just the **Add to Rust Search Extension** button's background color. Here is an example:

https://user-images.githubusercontent.com/3369694/151738891-ca270392-d1cf-435a-b907-4a88b5131beb.mov

Cc. @xnuk @NaturelLee

**Comment by Rapptz** [comment]
Looks okay. Not sure you meant to add the extra 2px border on all the other sides though, from my testing the bar looks a bit better if there's only one `border-left:` in both selectors, rather than `border` on the main one and `border-left` on hover.

**Comment by Folyd** [comment]
> Looks okay. Not sure you meant to add the extra 2px border on all the other sides though, from my testing the bar looks a bit better if there's only one `border-left:` in both selectors, rather than `border` on the main one and `border-left` on hover.

Good catch. Thanks for reminding me. All-sides transparent border is mistaken. 😄
