### ISSUE TITLE
Support search docs via path

### ISSUE THREAD

**Issue by Folyd** [huhu/rust-search-extension#148]
For example, input `parking_lot::lock_api::RwLockWriteGuard` in the address bar, would redirect to https://docs.rs/parking_lot/latest/parking_lot/index.html?search=RwLockWriteGuard.

**Comment by jaskij** [comment]
This is already implemented with with the `@` search. Searching for `@parking_lot RwLockWriteGuard` redirects to https://docs.rs/parking_lot/latest/parking_lot/?search=RwLockWriteGuard
