### ISSUE TITLE
Add additional Rust official books?

### ISSUE THREAD

**Issue by ian-h-chamberlain** [huhu/rust-search-extension#151]
Hi, it looks like there are some books that seem to be missing from the extension search which might be useful to add. Is this the complete list of supported books? https://github.com/huhu/rust-search-extension/blob/master/rust/src/tasks/books.json

From looking at https://www.rust-lang.org/learn :

* Rustdoc book: https://doc.rust-lang.org/rustdoc/index.html
* Rustc book: https://doc.rust-lang.org/rustc/index.html
* Command-line application book: https://rust-cli.github.io/book/index.html

If you'd be interested, I could open a PR to add these to the extension, in particular I think I would find the rustc book helpful to have easily searchable.

**Comment by Folyd** [comment]
Hi, @ian-h-chamberlain. Thanks for the suggestion. 

Rust extension has two different features related to Rust books.

- **One is the `:book` command which can list all Rust official books.** We already indexed nearly 30 books. https://github.com/huhu/rust-search-extension/blob/f781175da164882adad2fc7586ace4974a78dd01/extension/index/commands.js#L3-L30

![image](https://user-images.githubusercontent.com/3369694/160066769-59e5a3ea-484c-44a5-b35a-6ccb60a9477d.png)

- **Another one is book searching with `%` sigil.** You mentioned `book.json` file is the book list we can perform such a search.

![image](https://user-images.githubusercontent.com/3369694/160067529-811b09be-2754-4963-a15e-fa16c7259cb7.png)

Do you mean we should add additional books for the book search?

**Comment by ian-h-chamberlain** [comment]
@Folyd good to know there is a separate list for the `:book` command – I thought when I tried it that it was just using the same list (I couldn't find the `rustc` book there), but I think it's reasonable to have less than with `%`.

Of the books I suggested adding, I think it would be nice to include at least the Rustc book in `%` search, particularly for these sections:
* Lint listings: https://doc.rust-lang.org/rustc/lints/listing/index.html
* Codegen options: https://doc.rust-lang.org/rustc/codegen-options/index.html

Perhaps there is an additional issue with how the `:book` search works since it wasn't obvious to me. I will investigate more and open a separate issue based on what I find. Thanks!

**Comment by Folyd** [comment]
`:book` is just a simple command to filter books with keywords. 
![image](https://user-images.githubusercontent.com/3369694/160242393-1862da81-f618-46f0-9b9d-bdfc36e4686e.png)

Currently, `%` only support search book chapter titles. We need more endeavor to support search the heading title in markdown. I'll appreciate for contributions.

**Comment by Folyd** [comment]
Hi, @ian-h-chamberlain. v1.9.0 has been released. Now we can search rustc lints and Codegen options with `:rustc` command. See https://rust.extension.sh/changelog/#v1-9-0-2022-11-20 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/3369694/202908972-7c5b8448-5e88-4ae9-8266-d477b579b2eb.png">
