### ISSUE TITLE
The features dropdown buttons moves the "Go to latest version" button" after page load 

### ISSUE THREAD

**Issue by coderedart** [huhu/rust-search-extension#154]
usually on docs.rs, when you visit an outdated version docs page of a crate, we get this orange colored warning "Go to latest version" button on top left.

![image](https://user-images.githubusercontent.com/24411704/169522992-d0a43b18-1996-4300-880c-a0c4a65aa281.png)

but this extension moves the features dropdown button to the left of that yellow warning button. this happens after the page loads, so when i see the warning and try to click the "Go to latest version" link, I accidentally click the features button often. 
![image](https://user-images.githubusercontent.com/24411704/169523863-72f70f98-d8f2-4ce5-a588-969f8e0db207.png)

this happens because of the delay between the page loading and the extension doing its magic. 

this happens very often and frustrates me every time :(

Ideally, it would keep the features button where it already is, so that the orange `Go to latest version` button doesn't get pushed around.

**Comment by Folyd** [comment]
Hi, @coderedart. Thanks for your feedback. I cannot reproduce it. Which browser do you use?

**Comment by coderedart** [comment]
I use firefox. but i just checked in chrome too. same behavior. 
maybe your browser is too fast and loads it instantly. 
I open the docs.rs page and press `Ctrl + F5` to refresh the page multiple times.
here's the recording without rust extension in chrome.  the order of UI elements on top bar is the following:
Docs.rs -> bevy-0.3.0 version dropdown -> Go to latest version warning -> platform dropdown -> feature flags link

https://user-images.githubusercontent.com/24411704/169647836-d0ce445c-b2ec-486b-aaa6-83ee0343fabe.mp4

and here's the recording with the search extension. the order now changes *after* the page loads:
Docs.rs -> bevy-0.3.0 version dropdown -> **Feature Flags dropdown** -> Go to latest version warning -> platform dropdown

https://user-images.githubusercontent.com/24411704/169647993-c03233cc-2e51-43ab-b49f-d4619134540a.mp4

 the yellow warning first loads beside the version dropdown, but immediately is moved by the Feature flags dropdown. often when i try to click on the `Go to latest version` link, the feature flags drop down suddenly pops up, making me go back and *wait* for it appear this time, so that i can press the `Go to latest version` link after it is moved to right.


this is more often a problem when i'm browsing stackoverflow or other forums, which link to the older version docs.

**Comment by Folyd** [comment]
Ok, I see. Yes, the extension will reposition the feature flags button after the page is loaded for legacy reasons. I'll fix it ASAP.
