### ISSUE TITLE
Stopped working in Firefox

### ISSUE THREAD

**Issue by jaskij** [huhu/rust-search-extension#156]
Yesterday (23.05.2022) everything was fine. Today I came in to work and the plugin plain does not work - there's absolutely zero reaction to inputting `rs !tokio` in the omnibar. I tried disabling other extensions, it did not help. I am not sure what details, besides `About Firefox` would be helpful to you.

`about:addons` shows the plugin to be 1.6.0, last updated March 2, 2022

![image](https://user-images.githubusercontent.com/1429132/170034720-55c86ad3-4b14-4830-bc9d-bbcfd3e81bb6.png)

**Comment by Folyd** [comment]
That's weird. I cannot reproduce it. Did you try to relaunch the extension? Or reinstall the extension? Or you can enable the debug mode to inspect the console log.
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/3369694/170049795-925a9817-ffc8-4e5e-a473-4ce2a10155c5.png">

**Comment by jaskij** [comment]
Just in case of confusion, the system it worked on, and the system it does not work on are two different PCs (although both times using Firefox under Arch).

Relaunching the browser did not help, reinstalling the extension did.

Going to Debug Add-ons I got this:

![image](https://user-images.githubusercontent.com/1429132/170114667-ccbbed1d-d78a-4b63-a624-7bde1988f83f.png)
