### ISSUE TITLE
It seems `%` doesn't search the chapter title for its input

### ISSUE THREAD

**Issue by zjp-CN** [huhu/rust-search-extension#176]
![image](https://user-images.githubusercontent.com/25300418/177806845-61c1f5d5-2224-42bf-89e8-a6b0056005e8.png)

The [following](https://doc.rust-lang.org/reference/types/tuple.html) is not included in the search result.

![image](https://user-images.githubusercontent.com/25300418/177807044-ff3fdbdd-71e6-43fe-9921-a69c7364da50.png)

**Comment by zjp-CN** [comment]
![image](https://user-images.githubusercontent.com/25300418/177895035-f5d123da-10c2-4c28-9d6e-532b306048af.png)

Well, it's case sensitive.

**Comment by Folyd** [comment]
Actually, it's case insensitive. Is the first line in Screenshot #1 isn't you want?

**Comment by zjp-CN** [comment]
I missed it :) Thank you.
