### ISSUE TITLE
Alter plugin icon for dark themes

### ISSUE THREAD

**Issue by RileyMShea** [huhu/rust-search-extension#19]
With a dark theme on chrome, the extension logo blends into UI of the search bar. https://imgur.com/4PHOf3c

### Request:
Consider adding a white border shadow to the logo or another solution to address plugin logo visibility in black-themed browsers. 

Probably low priority since all functionality is implemented through `rs` in search bar.

OS: Ubuntu x64 19.10
- OS system theme: Adwaita-dark

Chrome: v80.0.x
- Chrome theme: [just black](https://chrome.google.com/webstore/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab)

**Comment by Folyd** [comment]
Thanks for the great suggestion. I'll fix this in the next version, maybe.

**Comment by Folyd** [comment]
Hello @RileyMShea, I just released version 0.9.0 which is dark theme compatible. Please check it out. :)

**Comment by RileyMShea** [comment]
Hey very cool! Thank you!
