### ISSUE TITLE
Search should be case sensitive

### ISSUE THREAD

**Issue by Victor-N-Suadicani** [huhu/rust-search-extension#194]
## Expected Behaviour
1. I type in `rs Eq`.
2. I hit enter.
3. I am taken to the docs for [`std::cmp::Eq`](https://doc.rust-lang.org/std/cmp/trait.Eq.html).

## Actual Behaviour (on Firefox for me at least)
1. I type in `rs Eq`.
2. I hit enter.
3. I am taken to the docs for [`std::ptr::eq`](https://doc.rust-lang.org/std/ptr/fn.eq.html).

This seems undesirable.

**Comment by Folyd** [comment]
Hi @Victor-N-Suadicani. Thanks for the feedback. I personally think case-sensitive has more disadvantages than advantages. For example, most traits, and structs are CamlCase, the users prefer to input lowercase keywords to search it, such as `refcell` for `RefCell`.

So, I still insist on the case-insensitive search experience.

**Comment by Victor-N-Suadicani** [comment]
I think the proper solution would be to weigh exact (case-sensitive) matches higher, but still find the other (case-insensitive) matches.

As in, `rs Eq` would still find both `std::ptr::eq` and `std::cmp::Eq` but `Eq` should be at the top because it matches exactly, while `eq` does not. Then searching `refcell` would still find `RefCell` (since there is nothing called `refcell`, `RefCell` would still be at the top).

**Comment by Folyd** [comment]
Good idea. Thanks.

**Comment by 13k** [comment]
You could also implement smart case search where if you type an upper case character in the query, it enables case sensitivity in the search, otherwise treats it as case-insensitive.

This way it doesn't require exact matches and it's easier to find case-sensitive partial matches (like `Once` => `OnceCell`).

**Comment by Folyd** [comment]
Rust Search Extension v2.0 has been released. This has been fixed in v2.0
https://github.com/huhu/rust-search-extension/releases/tag/v2.0.0
