### ISSUE TITLE
search clippy lints doesn't work

### ISSUE THREAD

**Issue by XyLyXyRR** [huhu/rust-search-extension#195]
![image](https://user-images.githubusercontent.com/39663597/190293372-703a2183-611d-4c82-bdcd-30efe64da4c9.png)

**Comment by Folyd** [comment]
Hi @XyLyXyRR. Thanks for the feedback. `e0002` isn't a normal clippy lint, do you mean an error code? If so, just input `e0002` (without `>`). However, `E0NAN` has been [fixed](https://github.com/huhu/rust-search-extension/commit/848cb3f3111943ee3aa631157c9053713370bff0).

**Comment by Folyd** [comment]
Here is the clippy hint searching example:
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/3369694/190306456-263fa6de-2b69-4da6-a632-109499b21446.png">

Here is the error code:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/3369694/190307073-bae06e2c-5248-4d63-baf3-c30de94ac9cc.png">
