### ISSUE TITLE
Searching external crates is not supported

### ISSUE THREAD

**Issue by Darksonn** [huhu/rust-search-extension#20]
Hey. I got sent here when I removed the extension again.
The feature I'm looking for is to search e.g. Tokio or futures docs for a certain term. I currently have firefox search bookmarks that allow this, but they just show the search results, and don't jump directly to the item, which is what I hoped this would allow me to do.

**Comment by Folyd** [comment]
@Darksonn Thanks for your feedback. We'll support search external crate's doc in the next version, please stay tuned. 
![image](https://user-images.githubusercontent.com/3369694/76377389-b82d5400-6385-11ea-8f91-9e82be44415e.png)

**Comment by Darksonn** [comment]
Good to hear! I would also love for a toggle to have the search-for-crate technique put me on the docs.rs page instead of crates.io

**Comment by Folyd** [comment]
@Darksonn Glad you love it. 😀

**Comment by Folyd** [comment]
Hey @Darksonn. Version 0.9.0 is released, which supports search external crate's docs on your address bar. :)
