### ISSUE TITLE
Failed to add `csv` crate

### ISSUE THREAD

**Issue by senden9** [huhu/rust-search-extension#219]
Hi!

I am using Firefox 107.0 with the latest search extension from the app store (1.9.1).

I can not add https://docs.rs/csv/latest/csv/ to my crate-list. The button is visible but not working:
![image](https://user-images.githubusercontent.com/905857/204451754-09a2311f-9bf0-46fb-bded-88d44d004045.png)
Other crates like [tokio](https://docs.rs/tokio/latest/tokio/) can be added from the docs.rs page.

Here is the JS-log when loading the site and before clicking anything else:
```
Uncaught TypeError: crateSearchDropDown is null
    setupSearchLoader https://docs.rs/main-20210305-1.52.0-nightly-51748a8fc.js:8
    <anonymous> https://docs.rs/main-20210305-1.52.0-nightly-51748a8fc.js:8
    <anonymous> https://docs.rs/main-20210305-1.52.0-nightly-51748a8fc.js:8
[main-20210305-1.52.0-nightly-51748a8fc.js:8:1189](https://docs.rs/main-20210305-1.52.0-nightly-51748a8fc.js)
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:1:149696
```
Here is the additional stuff that is coming to the log when clicking the "+ to Rust Serach Extension"-Button from the screenshot:
```
No search index found, start loading... [add-search-index.js:55:17](moz-extension://59e18a2f-d942-4fab-8ce2-7869759b1d07/script/add-search-index.js)
The script from “https://docs.rs/csv/1.1.6/csv/?search=search-indexnull.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
[csv](https://docs.rs/csv/latest/csv/)
Uncaught SyntaxError: expected expression, got '<'
[search-indexnull.js:1](https://docs.rs/csv/latest/search-indexnull.js)
Send search index success. [add-search-index.js:46:17](moz-extension://59e18a2f-d942-4fab-8ce2-7869759b1d07/script/add-search-index.js)
TypeError: right-hand side of 'in' should be an object, got undefined
[crate-manager.js:11:13](moz-extension://59e18a2f-d942-4fab-8ce2-7869759b1d07/crate-manager.js)
```

**Comment by Folyd** [comment]
Hi, @senden9. Thanks for the feedback. This is a bug. You can check this workaround: https://github.com/huhu/rust-search-extension/issues/177

**Comment by senden9** [comment]
Thanks for the speedy response @Folyd! I have no idea why it work but it works with clicking in the in-page-serachbar first.

As this seems to be an duplicate feel free to close that one. I only looked at the open reports for duplicates I think.
