### ISSUE TITLE
Extra sites: caniuse.rs, cheats.rs, etc.

### ISSUE THREAD

**Issue by CGMossa** [huhu/rust-search-extension#22]
There are golden sites beside the yet-pages, etc.

Personally, I am in love with [caniuse.rs](https://caniuse.rs/) and the [cheats.rs](https://cheats.rs/) has been instrumental whilst learning the ins-and-outs of Rust.

I don't have an idea as to how to integrate them.. So maybe this could be a good place to discuss this.

**Comment by Folyd** [comment]
It's feasible to integrate caniuse.rs data into this extension. However,  I couldn't promise the integration of cheats.rs as it could be a tricky thing. Thanks for your suggestion. :)

**Comment by Folyd** [comment]
Hey @CGMossa. v1.0.0 has been released, we now support caniuse.rs search thanks to @aquarhead's PR. See the [changelog](https://rust.extension.sh/changelog/) for more details.
