### ISSUE TITLE
Type of items is `undefined`

### ISSUE THREAD

**Issue by jakubdabek** [huhu/rust-search-extension#236]
Steps to reproduce:
1. Index a crate (or update an existing index), e.g. tokio
2. Search for a type or function, e.g. `@tokio TcpStream`
3. The extension redirects to <https://docs.rs/tokio/1.26.0/tokio/net/undefined.TcpStream.html>, while it should be `struct.TcpStream.html`. This doesn't happen if the indexed version of tokio is `1.25.0`.

Might be connected to #233

**Comment by Folyd** [comment]
Thanks for the feedback, #233 will fix this.
