### ISSUE TITLE
Remove or make optional enhancement to rust-lang repository's release page

### ISSUE THREAD

**Issue by acidghost** [huhu/rust-search-extension#238]
I have been using the extension for a while, it's amazingly useful. Thanks for the effort you put into it.

Unfortunately I had to disable the extension because it's become too high of a security risk for me. Giving away read capabilities to a critical website such as Github for a small enhancement is not worth it IMO.

I know that this is something that many users face and had to pass on the extension because of this. I see couple of solutions:
- make the feature optional and request permissions on-demand
- remove the feature entirely because it overlaps with the new features provided by the Github UI: you can already open a *searchable* outline of any markdown file

Speaking for myself, I never even used the feature.

**Comment by Folyd** [comment]
Fair enough. I'll remove this feature in the next version. Thanks for the feedback.
