### ISSUE TITLE
Can't add crates: Redeclaration of const storage

### ISSUE THREAD

**Issue by drewtato** [huhu/rust-search-extension#243]
Clicking the add or update button doesn't do anything.

This is similar to #177. I tried clicking the search bar just in case, but that didn't fix it. I couldn't find any other workaround.

Clicking the button causes this error to appear in the console:

```js
11:27:44.231 SyntaxError: redeclaration of const storage storage.js:1:1
    <anonymous> moz-extension://fdf66496-da98-4277-9c79-64af24759adf/core/storage.js:1
    inject resource://gre/modules/ExtensionContent.jsm:589
    AsyncFunctionNext self-hosted:810
```

I also tried reinstalling the extension, but same thing. Seems to be for every crate on docs.rs, but I first noticed on [`futures`](https://docs.rs/futures/0.3.27/futures/index.html).

RSE 1.9.1, Firefox 111.0.1 (64-bit), Windows 11

**Comment by Folyd** [comment]
Hi @drewtato, thanks for the feedback. https://github.com/huhu/rust-search-extension/commit/4933e1bf451d635eafb2c76a17e03dba2884809d fixed this bug. I'll release a new version soon.
