### ISSUE TITLE
`rs @tokio spawn` does not find any results

### ISSUE THREAD

**Issue by jorendorff** [huhu/rust-search-extension#250]
Searching Tokio is one of the examples illustrated on the web site with an animated GIF. It doesn't work for me in Chrome or Firefox. (Screenshots below are Firefox, but the behavior is about the same in Chrome.)

I definitely have Tokio indexed:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/283361/231207214-86a179a1-fe12-459c-bf15-8719243454b9.png">

Typing `rs @tokio` shows this:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/283361/231206885-a7ab1fdb-1dcc-4512-8c1c-1c2283002b90.png">

But searching for stuff in Tokio doesn't find anything. (There are [several functions called "spawn" in tokio](https://docs.rs/tokio/1.27.0/tokio/?search=spawn).)

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/283361/231207035-d34b4718-a441-48ce-8dfe-40b1f5a37215.png">

If I type `rs @tokio spawn` and press Return, nothing happens. The location bar goes back to showing the current URL.

**Comment by Folyd** [comment]
`v1.11.0` has been released.
