### ISSUE TITLE
Offline mode no longer works

### ISSUE THREAD

**Issue by SteveLauC** [huhu/rust-search-extension#252]
# Env
* Chrome: Version 112.0.5615.165 (Official Build) unknown (64-bit) (flatpak version, with proper file system permission given)
* Rust search extension: 1.11.1

# Steps to reproduce
1. Enable `offline mode` in the setting
2. Input the local doc path, `/home/steve/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/` in my case
3. Open a new tab, type `rs` and a space
4. Type `Vec`
5. Press the `Enter` key
6. And nothing happens

# Expected behavior
Doc for `std::vec::Vec` should be open.

# Possible cause
Maybe the local doc path configured is wrong, but in the following demo video, we can see that if we open the URL given by `Rust search extension`, the corresponding doc can be successfully loaded, which probably indicates that the configured path should just be fine.

# Demo
![2023-04-30 20-37-06](https://user-images.githubusercontent.com/96880612/235353705-344d65b2-cd80-4c59-807a-caa90298cdb5.gif)

------
Feel free to ask me anything that would help debug the issue:)

**Comment by Folyd** [comment]
Hi, @SteveLauC, thanks for the feedback. Prepending `file://` before your path should work, I guess Chrome doesn't think the URL is valid if the protocol is missing. However, this should be improved to auto-adding `file://` for the user.

**Comment by SteveLauC** [comment]
> Prepending file:// before your path should work

This works:)

> I guess Chrome doesn't think the URL is valid if the protocol is missing

This is true, I am so stupid hhhh

------------

Maybe an explicit document on how to enable this feature in section [Offline mode: search local Rust docs](https://rust.extension.sh/#offline-mode-search-local-rust-docs) would be great? I am happy to submit a patch to this [section](https://github.com/huhu/rust-search-extension/blob/master/docs/content/_index.md#offline-mode-search-local-rust-docs) if you want:)

**Comment by Folyd** [comment]
Thanks, feel free to improve the docs. 😄
