### ISSUE TITLE
Fuzzy Search std result intereferes

### ISSUE THREAD

**Issue by PSeitz** [huhu/rust-search-extension#262]
I typically use use the extension to jump directly to docs of a crate.

`rs tantivy` jumps to tantivy docs, but `rs ahash` jumps to https://doc.rust-lang.org/std/hash/index.html
There's no ahash on that webpage, so it seems that is a fuzzy search result.

Maybe related to https://github.com/huhu/rust-search-extension/issues/146

**Comment by Folyd** [comment]
Thanks for the feedback. This has been fixed in v2.0 (will release soon).
