### ISSUE TITLE
Offline mode no longer works in Chrome 118.0.5993.70

### ISSUE THREAD

**Issue by SteveLauC** [huhu/rust-search-extension#263]
### Env

* Chrome: Version 118.0.5993.70 (Official Build) unknown (64-bit)
* Rust Search Extension: 1.12.0
* Host: Fedora 38 Workstation/GNOME 44.5
* Rust: 
    
   ```sh
   $ rustup -V
   rustup 1.26.0 (5af9b9484 2023-04-05)
   info: This is the version for the rustup toolchain manager, not the rustc compiler.
   info: The currently active `rustc` version is `rustc 1.73.0 (cc66ad468 2023-10-03)`
   ```

### Erroneous Behavior

Choose the entry I want to check, press enter, nothing happens

### Steps to reproduce

1. Enable the offline mode with the following path
    
    ```
    file:///home/steve/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/
    ```

    > the path should be right:
    >
    > ```sh
    > $ rustup doc --std --path
    > /home/steve/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/std/index.html
    > ```

2. Open a new tab
3. input `rs`, the a space
4. input `Vec`, choose `std::vec::Vec`, press the enter button

### Workaround I have tried

1. Restart chrome
5. Reinstall the extension

### Demo

[Screencast from 2023-10-16 12-15-17.webm](https://github.com/huhu/rust-search-extension/assets/96880612/603b97db-1fd4-4d5a-8d20-db8314121c18)

**Comment by Folyd** [comment]
Thanks for the feedback. Chrome has restricted access to local file URLs since 118.0, see the announcement and workaround here: https://developer.chrome.com/docs/extensions/whatsnew/#changes-to-file-scheme

**Comment by Folyd** [comment]
Neither for me to find that setting. 🥲 Maybe you can change to this workaround: https://rust.extension.sh/faq/#why-local-file-rust-doc-not-work-properly-on-firefox

**Comment by SteveLauC** [comment]
Get it, I don't want to spawn a server just for serving local file accesses so I think I will just use the online doc for the moment, thanks for looking into the issue!

**Comment by yescallop** [comment]
In the post provided by the Chrome annoucement I found this [potential solution](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/ZtCvVISQU54/m/Qv_wCnnUAQAJ):

> I ended up adding "optional_host_permissions": [ "file:///*" ]
> This way the "Allow access to file URLs" is shown, navigation works, but I don't actually get read permission.

Maybe we can give it a try?
