### ISSUE TITLE
How to actually use it is not explained anywhere

### ISSUE THREAD

**Issue by marshray** [huhu/rust-search-extension#266]
After installing the extension on MS Edge, I find nothing in [the extension store page](https://microsoftedge.microsoft.com/addons/detail/rust-search-extension/olemfibpaicdoooacpfffccidjjagmoe) or the installed extension page (extension://olemfibpaicdoooacpfffccidjjagmoe/manage/index.html) that says anything about how to use it.

I have also been through the extension settings.

The Edge Extensions page "edge://extensions/shortcuts" allows me to set a keyboard shortcut for the extension. But this keyboard shortcut just takes me to the useless "Rust Search Extension" page.

I assume there is some special key sequence that needs to be typed, but without knowing what that is, this extension is useless to users.

Also, I see indication there is some way I can "index crates". That sounds useful, but there is not even a hint about how I would do that.

Thank you :-)

**Comment by Folyd** [comment]
Hi @marshray. You can check the README and official website to learn how to use the extension. :)
- https://github.com/huhu/rust-search-extension#how-to-use-it
- https://rust.extension.sh/

<img width="804" alt="image" src="https://github.com/huhu/rust-search-extension/assets/3369694/7de75981-30a6-47ac-9c2e-77618ffff721">
