### ISSUE TITLE
std lookup stops working after some time

### ISSUE THREAD

**Issue by kesyog** [huhu/rust-search-extension#269]
After some time, the Chrome extension stops showing any results from std, which is my primary use case for it. Only the names of third-party crates show up in my results, even though I'm not using the `!` sigil.

A few observations:
* Running `:update` does not fix the issue
* Other search types still work: crate search via `!`, nightly search via `/`, etc.

I peeked at the extension's storage via `chrome.storage.local.get(null, function(result) { console.log('Value: ', result); });`, and the `index-std-stable` key is empty (`{}`) when this bug is encountered.

I've been able to temporarily fix this issue in a couple of ways:
1. Re-installing the extension
2. Removing the `index-std-stable` key via `chrome.storage.local.remove("index-std-stable")` and restarting Chrome, though I haven't tested this rigorously.

**Comment by kesyog** [comment]
Running 1.13.0 (but I've seen this before today's release as well) and Chrome 121.0.6167.184

**Comment by Folyd** [comment]
Hi @kesyog, thanks for the feedback. If you open the [std docs](https://doc.rust-lang.org/std) page, the extension will sync the latest search index, then it should be fixed automatically. If not, try to remove this item from `localstorage` and refresh the page again. It should works.
<img width="786" alt="image" src="https://github.com/huhu/rust-search-extension/assets/3369694/dcaf2644-50d8-4a7a-b770-6f40f6584b8f">

**Comment by kesyog** [comment]
Hey, it's working better now after opening the std docs page to refresh the index. I sometimes need to delete my query and retype it for any results to show up (a totally separate issue), but so far I haven't been able to reproduce the issue where the index is totally gone.

**Comment by kesyog** [comment]
Closing this issue since I can no longer reproduce it with the 1.13.0 after opening the std docs . Thanks!
