### ISSUE TITLE
How to search？

### ISSUE THREAD

**Issue by linonetwo** [huhu/rust-search-extension#271]
Hi, thanks for dev this. 

But I can't find usage guide in moz-extension://3579404e-b39b-704a-a01e-aa703171f1f6/manage/index.html , it is inconvenient. I have to open https://rust.extension.sh/#search-docs instead.

And in https://rust.extension.sh/#search-docs, the gif immediately show 
![截屏2024-02-26 15 11 37](https://github.com/huhu/rust-search-extension/assets/3746270/ee4777fd-41c4-49ac-8399-6aa6bb08e1b7)

My eyes are too old to see how it is triggered. And there is no obvious doc about how to trigger it. This is a thing that can be improved in the doc.

**Comment by linonetwo** [comment]
use `rs` to trigger. But doc may still can be improved.

**Comment by Folyd** [comment]
Thanks for the feedback. Yes, input `rs` to search, I'll improve the docs.
