### ISSUE TITLE
Indexing is broken in the latest version

### ISSUE THREAD

**Issue by WaffleLapkin** [huhu/rust-search-extension#272]
When I do `rs @some_indexed_crate query` the search works fine, but the search results are all broken URLs.

Screenshot examples for query `rs @teloxide Update` (ALL suggested urls are broken):
![2024-03-05_13-30](https://github.com/huhu/rust-search-extension/assets/38225716/aae6692b-e800-499d-b29f-140fbe21cad9)
![2024-03-05_13-30_1](https://github.com/huhu/rust-search-extension/assets/38225716/1cf30ea2-74e5-4912-8d21-483b1e38e98c)

A correct result would be:

![2024-03-05_13-31](https://github.com/huhu/rust-search-extension/assets/38225716/9a911673-408e-4bc2-b452-4dcf0a5eb26d)

Extension version: 1.13.0
Browser: firefox 122.0.1

**Comment by yescallop** [comment]
Bisecting reveals that 4cca580 is the first bad commit. This seems like a `rustdoc` version compatibility issue considering that indexing works well for the latest `tokio` doc.

**Comment by yescallop** [comment]
Quick notes: One possible solution for this is to use the `itemTypes` provided by the `search-*.js`. Another is to parse the date in the filename `search-index-*.js` and opt for the new or old `itemTypes` based on the date.
