### ISSUE TITLE
Search ignoring dashes and underscores

### ISSUE THREAD

**Issue by jaskij** [huhu/rust-search-extension#287]
When I search for [`bit-vec`](https://docs.rs/bit-vec/latest/bit_vec/), the extension instead redirects me to [`bitvec`](https://docs.rs/bitvec/latest/bitvec/)

**Comment by Folyd** [comment]
Hi @jaskij, you can try my new product: https://query.rs/?q=bitvec

**Comment by jaskij** [comment]
@Folyd does it mean you're dropping the extension?

Also, query.rs *also* doesn't work right. Searches for both `bit-vec` and `bit_vec` have `bitvec` as the top result.

**Comment by Folyd** [comment]
Ok, I see. Rust Search Extension will release version 2.0 soon. Query.rs has no plans or capability to replace the extension.

**Comment by Folyd** [comment]
Hi, I improve the searching algorithm: https://query.rs/?q=bit-vec, this changes will be included in Rust Search Extension v2.0.

**Comment by jaskij** [comment]
Thanks, that looks good.
