### ISSUE TITLE
Threads in Dropdown Menu Do Not Open in New Tab

### ISSUE THREAD

**Issue by Aaronlalala** [huhu/rust-search-extension#288]
## Description
When using the dropdown menu to navigate to different threads, clicking on a thread does not open it in a new page/tab. This makes me to go back and forth between the doc and the main page when trying to view multiple docs page simultaneously.

But I am not sure if it's caused by my browser's default setting. Thank you! This is really useful for me to learn Rust.

## Steps to Reproduce
Navigate to the main page type anything to get a dropdown menu. Click on any thread in the dropdown menu. 
<img width="500" alt="image" src="https://github.com/user-attachments/assets/7c0698e2-1690-484b-8b46-80e3db4230e6">

**Comment by Folyd** [comment]
Hi @Aaronlalala, thanks for the feedback. You can use `ALT + Enter` to open in the new tab:

<img width="237" alt="image" src="https://github.com/user-attachments/assets/2fe39870-61cf-430e-8d30-2dcaa91a9310">


BTW, here is the rust search extension repo, not query.rs. :)

**Comment by Aaronlalala** [comment]
Hi @Folyd, thanks for getting back to me. That's awesome. It really helps!
