### ISSUE TITLE
Feature flags: should optional dependencies also show in feature flags?

### ISSUE THREAD

**Issue by jmjoy** [huhu/rust-search-extension#29]
Just a advise, like:

https://github.com/servo/rust-url/blob/28314752bf138a87bd8151f610d385629dec5710/Cargo.toml#L43

There is no `[features]` section in `Cargo.toml`, but `serde` is a feature of `url`, I can use it in my `Cargo.toml`:

```toml
url = { version = "2.1.1", features = ["serde"] }
```

So should this optional dependency show in `Feature flags`?

**Comment by Folyd** [comment]
Sounds good. Thanks for the suggestion and welcome to give PR. :)

**Comment by jmjoy** [comment]
I'm not familiar with JS. :joy:

**Comment by Folyd** [comment]
Hi, @jmjoy. We finally support show option dependencies!👏👏 See https://github.com/huhu/rust-search-extension/commit/8b81fc70fbeb1579ff30c29529a5ee3466ecd463.

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/3369694/156170810-f82cc06d-2dd4-4aa8-99d8-becead13ade1.png">
