### ISSUE TITLE
big random checkmark in new update

### ISSUE THREAD

**Issue by joshka** [huhu/rust-search-extension#292]
Why does this happen?

<img width="1157" alt="image" src="https://github.com/user-attachments/assets/d22a5ab7-d61b-4214-80e3-063f8c1120bf">

Removing the extension and re-adding seems to fix it up, but it's worth bearing in mind that this may be what users that upgrade see.

**Comment by Folyd** [comment]
Hello, are you using the v2.0? I just released the v2.0, this should been fixed.

**Comment by joshka** [comment]
Yeah, this happened the other day. As mentioned, removed and re-added to fix it, so I don't have details on the reason this was coming up. Mentioning for your awareness more than needing a fix.

**Comment by joshka** [comment]
Closing as this was an intermittent issue when upgrading
