### ISSUE TITLE
The extension doesn't work

### ISSUE THREAD

**Issue by israteneda** [huhu/rust-search-extension#31]
The extension doesn't work I search for rust docs in search tab but google results appear. I use Firefox on Ubuntu.

**Comment by Folyd** [comment]
Thanks for your feedback. Did you input the keyword `rs` then press `Space` to search the docs?

**Comment by israteneda** [comment]
Yes works, but the icon of extension don't show properly, it's showed the default extension icon in the toolbar search.

**Comment by Folyd** [comment]
@israteneda That is the default behavior of Firefox, which is different from Chrome. :)

**Comment by israteneda** [comment]
Ok @Folyd, thank you very kind.
