### ISSUE TITLE
Do not open changelog tab automatically

### ISSUE THREAD

**Issue by CreepySkeleton** [huhu/rust-search-extension#32]
First of all, thank you for the extension! It works very nice and neat.

Sometimes, when the extension gets updated, it automatically opens https://rust-search-extension.now.sh/changelog/ in a new tab, immediately changing focus to it. This is annoying, especially when you're preoccupied with other stuff to read.

Would it be possible to add a setting for "automatically open changelog on updates, on/off"?

The browser is Firefox 75.0

**Comment by Folyd** [comment]
@CreepySkeleton Sorry for the inconvenience. I'll fix that. Thanks for your feedback.

**Comment by Folyd** [comment]
This got fixed on version 0.10.0. See the [changelog](https://rust-search-extension.now.sh/changelog/).
