### ISSUE TITLE
When you're on the [src] page of a crate's doc, the extension thinks the crate is not added yet

### ISSUE THREAD

**Issue by Boscop** [huhu/rust-search-extension#44]
When you're on the `[src]` page of a crate's doc, the extension thinks the crate is not added yet.
Steps to reproduce:
Go to any crate's doc, add the crate to this search extension using the Plus sign.
Click on a symbol's `[src]`. Note that the extension button shows the plus sign again instead of the checkmark.

**Comment by Folyd** [comment]
Hugely thanks for the feedback. I'll fix that in the next version.
