### ISSUE TITLE
Cannot set offline std doc path

### ISSUE THREAD

**Issue by Ionizing** [huhu/rust-search-extension#49]
The 'Options' button is gray, which means I cannot set the offline std doc path
<img width="319" alt="image" src="https://user-images.githubusercontent.com/17506747/82857251-114b6380-9f43-11ea-8f17-1445c9990fc8.png">

Also there is no "Allow file path access" option in settings tab of rust search extension
<img width="674" alt="image" src="https://user-images.githubusercontent.com/17506747/82857313-38a23080-9f43-11ea-9930-4bdf63597555.png">

# Here is the info of my machine
OS: macOS 10.15.1
Chrome: Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by Folyd** [comment]
Thanks for the feedback. You can click the Rust Search Extension icon on the toolbar directly instead of right-clicking to select options. Sorry, this extension has no options page.

**Comment by Ionizing** [comment]
Well, ~~nothing happens when I LEFT click that button ..~~

It seems the time gap between the popup and the click is a little long for the first time. I misunderstood that nothing would happen if I click that button. 

Issue solved, thank you very much!
