### ISSUE TITLE
The normal preferences mechanism should be used, rather than using a toolbar icon

### ISSUE THREAD

**Issue by chris-morgan** [huhu/rust-search-extension#6]
This extension uses a toolbar icon for modifying preferences only. I haven’t the foggiest about Chrome, but certainly in Firefox this is wrong: there’s a preferences mechanism whereby you can put such things with the rest of the add-on configuration (like whether it’s enabled or disabled) in about:addons.

**Comment by acdenhartog** [comment]
This is not a thing anymore, `about:addons` no longer contains preferences *for any addon*. Instead `...` can include a link to options, which is a separate page, and it might as well link to `popup/index.html`. Users can simply hide the toolbar button themselves when they do not need it. So in my opinion add to the manifest: `"options_ui": {
    "page": "popup/index.html"
}`, and this issue can be closed.

**Comment by onekirne** [comment]
It is not worth maintaining a separate options page, so in my opinion just add to the manifest `"options_ui": {
    "page": "popup/index.html"
},` and this issue can be closed. Users can simply hide the toolbar button themselves when they do not need it anymore.

**Comment by Folyd** [comment]
This has been fixed.
