### ISSUE TITLE
Allow removing `rust` shortcut

### ISSUE THREAD

**Issue by Erutuon** [huhu/rust-search-extension#71]
I use this extension in Firefox. At the moment the extension uses both `rust` and `rs` as shortcuts, but most often when I type `rust` plus something into the address bar, I want to search in my browser's configured search engine (DuckDuckGo). I have often clicked enter without thinking, and instead of seeing the DuckDuckGo results, I see the search results from my local copy of the Rust documentation, which doesn't include the result I'm looking for. To use DuckDuckGo I have to add `?` at the beginning of the query so that the extension doesn't take over.

Could the extension allow choosing whether `rust` is a shortcut or not? I'd prefer to only have the shortcut `rs`. (This was my bookmarks shortcut for searching https://doc.rust-lang.org/, before I installed the Rust search extension.)

**Comment by Folyd** [comment]
Hi @Erutuon. `rs` is the only keyword to trigger search extension. Does the keyword `rust` is the Firefox keyword or [Duckduckgo bang](https://duckduckgo.com/bang)? Could you please share more detail about that? Thanks.

![image](https://user-images.githubusercontent.com/3369694/85247682-30c1a780-b481-11ea-8758-3aa9426d196d.png)

**Comment by Erutuon** [comment]
I'm sorry for the noise. You're right. The `rust` keyword was in my own bookmarks. I should have checked my bookmarks before posting this issue.
