### ISSUE TITLE
Remind me of "rs"

### ISSUE THREAD

**Issue by bestouff** [huhu/rust-search-extension#72]
I keep forgetting I have to type `rs` to activate the extension (please don't laugh), and each time I have to go to the website, realize it's not written anywhere here (and doesn't appear in the featured videos), then go to github and find the information.  

So could you please add something like "type `rs` to activate rust search" prominently on the website *and* in the sort-of "about box" which appears when I click on the rust icon next to the search bar ?

**Comment by Folyd** [comment]
Hi @bestouff. Thanks for your kind suggestion. We did mention "type `rs` to activate rust search" on the websites. However, we didn't realize that it's not easy for the user to find. So, we really need some change to improve this. 😸

**Comment by xxchan** [comment]
The issue can be closed?
