### ISSUE TITLE
Searches should prioritize std over core and alloc

### ISSUE THREAD

**Issue by johnw42** [huhu/rust-search-extension#75]
In Firefox, when I type `rs cow` into the address bar, I get taken to [`alloc::borrow::Cow`](https://doc.rust-lang.org/alloc/borrow/enum.Cow.html), which seems fine, but then if I follow the links from there to [`core::iter::FromIterator`](https://doc.rust-lang.org/nightly/core/iter/trait.FromIterator.html), the implementations for `Cow` aren't listed. I was confused enough that I almost filed a bug against rustdoc, but then I realized that if I start from [`std::borrow::Cow`](https://doc.rust-lang.org/std/borrow/enum.Cow.html), the corresponding link takes me to [`std::iter::FromIterator`](https://doc.rust-lang.org/std/iter/trait.FromIterator.html), which lists all the implementations as expected.

I think the solution here is to treat `core` and `alloc` as special cases and always prefer the docs for the `std` version of names in those crates.

**Comment by xxchan** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/37948597/196663802-b96ce6d5-b254-498a-912e-9227ad67fef4.png">
seems fixed

**Comment by Folyd** [comment]
We only index **std**, **proc_macro**, and **test** crate in the standard library, so this can be closed.
