### ISSUE TITLE
"to Rust Search Extension" button breaks docs.rs header

### ISSUE THREAD

**Issue by CreepySkeleton** [huhu/rust-search-extension#79]
The vanilla header looks like this:

![image](https://user-images.githubusercontent.com/50968528/96385993-39f92180-11a0-11eb-880d-3f46002f752d.png)

With extension installed and activated:

Firefox:

![image](https://user-images.githubusercontent.com/50968528/96386053-a7a54d80-11a0-11eb-8ce1-2dfd2e49fea2.png)

Chrome (only on some crates, e.g [`proc-macro-error`](https://docs.rs/proc-macro-error/1.0.4/proc_macro_error/)):

![image](https://user-images.githubusercontent.com/50968528/96386097-f94dd800-11a0-11eb-912f-54e4b782db09.png)

This never hapenned until recently.  Docs.rs devs probably changed layout or something.

**Comment by Folyd** [comment]
Thanks for the feedback. Docs.rs did have some changes recently, could be this [commit](https://github.com/rust-lang/docs.rs/commit/46b3867bf5f7cab5167017559db05f9e96ee398c)? Anyway, I'll fix it in the next version. :)

**Comment by Folyd** [comment]
Hi @CreepySkeleton. Version 1.0.0 has been released. I'll close this issue, free feel to file a new one if you have any further questions. Thanks a lot.

**Comment by CreepySkeleton** [comment]
I confirm that the issue has been fixed. Thank you greatly!
