### ISSUE TITLE
Feature flags no longer showing

### ISSUE THREAD

**Issue by iulianR** [huhu/rust-search-extension#82]
Hello, the Feature Flags menu in the header is great. I found out very recently that it's a feature of rust-search-extension, and not of docs.rs, when the menu stopped working. All crates show as having no features.

Is there another issue I can track for this? Can you reproduce? Thanks!

**Comment by Folyd** [comment]
Huge thanks for the feedback. Same issue with #79. I'll release a new version soon, see the [changelog page](https://rust.extension.sh/changelog/).

**Comment by Folyd** [comment]
Hi @iulianR. Version 1.0.0 has been released. I'll close this issue, free feel to file a new one if you have any further questions. Thanks a lot.
