### ISSUE TITLE
how to search rustc docs?

### ISSUE THREAD

**Issue by LiuTianjie** [huhu/rust-search-extension#83]
The extension is so great! But I still wonder whether it supports rustc crates?

**Comment by Folyd** [comment]
I have no idea about it. There are no docs for **rustc** in the docs.rs. Do you have any suggestions?

**Comment by LiuTianjie** [comment]
> I have no idea about it. There are no docs for **rustc** in the docs.rs. Do you have any suggestions?

maybe I mean this https://doc.rust-lang.org/nightly/nightly-rustc/

**Comment by Folyd** [comment]
Hi @LiuTianjie. v1.2.0 has been released and we can now search rustc docs! See changelog: https://rust.extension.sh/changelog/

Thanks for your feedback!
