### ISSUE TITLE
Allow specifying docs.rs as default for crate searches

### ISSUE THREAD

**Issue by seritools** [huhu/rust-search-extension#85]
I've noticed that I use `!!crate` about 95% of the time, so it would be awesome if there was a setting to go to docs.rs by default when selecting a crate from the dropdown, and resort to `!!` for crates.io.

**Comment by Folyd** [comment]
Nice suggestion, thanks. Actually, as the author, I feel the same as you. 🤣

**Comment by Folyd** [comment]
Hey, v1.1.0 has been released. Now the docs.rs is the default crate search. 🎉

**Comment by seritools** [comment]
Very nice, thanks a lot!
