### ISSUE TITLE
Always shows update page

### ISSUE THREAD

**Issue by sirxyzzy** [huhu/rust-search-extension#88]
Every time I start a new instance of Edge (I'm using the beta version, on 64 bit Windows 10) the extension shows the update page,.. https://rust.extension.sh/update

Can this be shown just once?

**Comment by Folyd** [comment]
You can turn off the auto-update on the popup page.
![image](https://user-images.githubusercontent.com/3369694/99541397-be330480-29eb-11eb-947a-6665702188cc.png)

**Comment by sirxyzzy** [comment]
Ah, I see, thanks, personally I would rather it was able to update silently, but disabling update will work for me

**Comment by Folyd** [comment]
You are welcome. Unfortunately, we can't achieve a silent update due to the limitations of the browser API. However, you can use `:update` command to update manually. :)
