### ISSUE TITLE
Docs.rs header is broken once again

### ISSUE THREAD

**Issue by CreepySkeleton** [huhu/rust-search-extension#89]
![image](https://user-images.githubusercontent.com/50968528/100311163-2ff8e880-2fc0-11eb-8b93-0ce03db40e83.png)

(Screenshot taken in Firefox 83.0)

__Triggers only if the crate's name + version is long enough, like [`glommio-0.2.0-alpha`](https://docs.rs/glommio/0.2.0-alpha/glommio/)__, e.g [`syn`](https://docs.rs/syn/1.0.51/syn/) doesn't trigger it.

**Comment by Lythenas** [comment]
I can confirm this. But the docs.rs header is also broken without the extension if the width of the browser window is to small. If the window is small enough the text in the header disappears and it look normal again. This is probably also an issue with docs.rs but the extension exaggerates it.

**Comment by Folyd** [comment]
> I can confirm this. But the docs.rs header is also broken without the extension if the width of the browser window is to small. If the window is small enough the text in the header disappears and it look normal again. This is probably also an issue with docs.rs but the extension exaggerates it.

yes, you're right. Especially, docs.rs officially added a feature-flags menu in the header bar recently, the header bar gets more crowded. I'm not sure whether there is more menu that would be added in the future. Therefore, I have some incline to move the "Add to Rust Search Extension" button to the bottom of the Rust/crate logo. 
![image](https://user-images.githubusercontent.com/3369694/100347395-3f0f8300-3020-11eb-8fcd-e47291648164.png)

**Comment by Folyd** [comment]
Hello, v1.1.0 has been released! We have good compatibility with the official feature flags menu. So we remain the "Add to" button in the same position.
