### ISSUE TITLE
This page pops up every time you boot up and open the browser

### ISSUE THREAD

**Issue by nm2675257** [huhu/rust-search-extension#91]
![QQ图片20201204085247](https://user-images.githubusercontent.com/51024118/101107963-74166980-360e-11eb-9bc6-9596334cf7aa.png)

**Comment by Folyd** [comment]
Hey @nm2675257, you can turn off the auto-update on the popup page. See #88. I'll add a reminder on the update page. Thanks for your feedback. :)
