### ISSUE TITLE
Offline mode does not work in Firefox

### ISSUE THREAD

**Issue by burjui** [huhu/rust-search-extension#94]
I am using Firefox 84.0.1 on Manjaro and have `rust-docs` installed. I enabled offline mode and set the path to `file:///usr/share/doc/rust/html/`. Search itself works fine: for example, when I type "rs result" into the search box, it shows me a bunch of results with correct local paths, such as `file:///usr/share/doc/rust/html/std/fmt/type.Result.html`. But when I hit Enter, nothing happens. I tried the same with Chromium and everything works fine.

**Comment by Folyd** [comment]
Hi @burjui. Thanks for reporting. This is a known issue for Firefox, see the [FAQ](https://rust.extension.sh/faq/#why-local-file-rust-doc-not-work-properly-on-firefox).

**Comment by burjui** [comment]
Ah sorry, thought it was a bug. Thankfully, there's a workaround. Thanks!

**Comment by burjui** [comment]
By the way, I didn't know that this is not a bug, because I discovered the feature by accident, not from the website. Maybe you could add some kind of hint to this feature on Firefox, so that users immediately know about this unfortunate `file:` issue? Something like a balloon message over the local doc text field.

**Comment by Folyd** [comment]
> By the way, I didn't know that this is not a bug, because I discovered the feature by accident, not from the website. Maybe you could add some kind of hint to this feature on Firefox, so that users immediately know about this unfortunate `file:` issue? Something like a balloon message over the local doc text field.

Great suggestion! I'll do it. 👍
