### ISSUE TITLE
Chrome extension required permissions now include data access to github.com

### ISSUE THREAD

**Issue by mtnmts** [huhu/rust-search-extension#95]
I noticed that the new update requires full data permissions to github.com, this being version 1.1.0 from Jan 5th.
I went over the change-log and I've seen no mention for this.

if this is an intended change it would be very helpful if it would be mentioned in the change-log as full-data access to github.com is pretty major, especially for an extension catering to developers.

Thanks for all the work on this great extension, I use it all the time :)

**Comment by Folyd** [comment]
Hey @mtnmts. Thanks for the feedback. I added a new access permission declaration to the [changelog](https://rust.extension.sh/changelog/) and [FAQ](https://rust.extension.sh/faq/#why-the-extension-requires-access-to-github-com) pages.
