### ISSUE TITLE
Don't require people to explicitly add crates for their docs.rs page to be accessible

### ISSUE THREAD

**Issue by Michael-F-Bryan** [huhu/rust-search-extension#96]
It'd be nice if you didn't need to explicitly click the *"⊕ to Rust Search Extension"* button on a crate's docs.rs page in order to search for items inside it.

# Expected Behaviour

If you enter `rs @itertools::XXX` it would first try to find the corresponding page if already added and indexed, falling back to opening the search page (https://docs.rs/itertools/?search=XXX).

# Actual Behaviour

Typing `rs @itertools::Itertools` and hitting `<enter>` just clears the search box and does nothing.

Typing `rs !itertools::Itertools` will navigate to https://docs.rs/releases/search?query=itertools%3A%3AItertools, i.e. it tries to find the `itertools::Itertools` crate in docs.rs.

**Comment by Folyd** [comment]
Thanks for the feedback. 

I'd love to have an auto integration with all third-party crates. But, we can't, due to the limited disk size available to extension and the suck permission the browser granted to us. Hence, we need the user to add their most concerned crate to the extension manually, and that just a one-time button-click per crate. 

> If you enter rs @itertools::XXX it would first try to find the corresponding page if already added and indexed, falling back to opening the search page (https://docs.rs/itertools/?search=XXX).

Great suggestion, I'll add a fallback strategy.

BTW, you can prefix `~` before the keyword to search across all your favorite crates without using `@crate-name`. `~` also supports qualified path search while the `@` can't. For example, `~itertools::Itertools`. See [the docs](https://rust.extension.sh/#search-external-crate-docs).

**Comment by Michael-F-Bryan** [comment]
> Hence, we need the user to add their most concerned crate to the extension manually, and that just need a one-time button-click per crate.

> BTW, you can prefix ~ before the keyword to search across all your favorite crates without using @crate-name. ~ also supports qualified path search while the @ can't. For example, ~itertools::Itertools. See the docs.

Yeah, I'm not saying we download the docs for every crate on crates.io (which isn't practical), merely that it will try to gracefully fall back to the crate's search page when it isn't indexed.

At the moment, the UX isn't that great because `~` will only work when you've added the crate.

https://user-images.githubusercontent.com/17380079/104159431-43ee9180-542a-11eb-86be-6791d45b921d.mp4

As an alternate idea, what about automatically adding a crate's docs to the index whenever you look it up on docs.rs? Then you could use some sort of LRU system to make sure disk usage stays below a certain threshold.

That leaves you with the same limitation that you need to have visited a crate's docs at least once before it is searchable, though. This limitation is what originally triggered this issue because I hadn't visited `itertools` in the months I've been using this extension.

**Comment by Folyd** [comment]
Thanks for your screen video, which speaks aloud.
> As an alternate idea, what about automatically adding a crate's docs to the index whenever you look it up on docs.rs? Then you could use some sort of LRU system to make sure disk usage stays below a certain threshold.

Ok, I see. Theoretically, it's feasible to automatically add a crate's search index whenever you open that crate's docs page. However, I don't think this auto behavior is suitable for all users. Personally, I look up a crate's docs doesn't mean I need to search it. In most cases, I just give a peek at it. On the other hand, the user will easily get confused when we use the LRU algorithm to invalidate the old indexed crate.

**Comment by Michael-F-Bryan** [comment]
> On the other hand, the user will easily get confused when we use the LRU algorithm to invalidate the old indexed crate.

Fair point. You could probably split the LRU into "explicitly indexed" and "automatically indexed", but that's just adding more complexity when people could just add the item themselves.

How much disk space do you get to work with, by the way?

**Comment by Folyd** [comment]
> but that's just adding more complexity when people could just add the item themselves.

Exactly. 

> How much disk space do you get to work with, by the way?

My extension use `localStorage` and browser `storage` API to persistent those offline search index, each API limit to 5M (amounted to 10M in total).

**Comment by phiresky** [comment]
To be honest, whether or not I get autosuggestions in the address bar is not very important to me because most of the time I will look at the full docs page anyways. So it would be really helpful that if I do `rs @procfs dropcache` it will just go to https://docs.rs/procfs/?search=dropcache when I don't have `procfs` indexed.

**Comment by Folyd** [comment]
> To be honest, whether or not I get autosuggestions in the address bar is not very important to me because most of the time I will look at the full docs page anyways. So it would be really helpful that if I do `rs @procfs dropcache` it will just go to https://docs.rs/procfs/?search=dropcache when I don't have `procfs` indexed.

Nice suggestion. This is in the plan. Stay tuned. 😺
